//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class jasenet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jasenet()
        {
            this.maksettu = 0;
        }
    
        public int avain { get; set; }
        public string hetu { get; set; }
        public string snimi { get; set; }
        public string enimet { get; set; }
        public string osoite { get; set; }
        public int postinumero { get; set; }
        public string postitoimipaikka { get; set; }
        public string puhelinnumero { get; set; }
        public string email { get; set; }
        public System.DateTime liittymispv { get; set; }
        public int maksettu { get; set; }
        public string lisatietoa { get; set; }
    }
}
